apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: transcation-rs
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-app
          image: muralisocial123/transcation-image:latest
          ports:
            - containerPort: 3000
