apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-cont
        image: muralisocial123/clahan-web-project:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: web-svc 
spec:
  selector:
    app: web 
  ports:
    - port: 82 
      targetPort: 80
      protocol: TCP 
  type: LoadBalancer                
